name: Exécuter les tests Pytest

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Lancer les tests avec pytest
        run: |
          pytest
