name: pytest test.py by Augustin

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest test.py
